#ifndef MACROS_H
#define MACROS_H

#define CTRL(x) ((x) & 31)

#define _MAIN_THEME 1
#define _LINE_NUMBER_COLOR 2

#define INIT_MAIN_THEME() init_pair(_MAIN_THEME, COLOR_WHITE, COLOR_BLACK)
#define INIT_LINE_NUMBER_THEME() init_pair(_LINE_NUMBER_COLOR, COLOR_CYAN, COLOR_BLACK)

// THEMES DEFINITION
#define MAIN_THEME COLOR_PAIR(_MAIN_THEME)
#define LINE_NUMBER_THEME COLOR_PAIR(_LINE_NUMBER_COLOR)

#endif